### PR TITLE
fixing string issues in module_args declaration in borgbase_repo.py

### PR DESCRIPTION
**Pull request by aurelpere**
Hi,
I just tested the ansible playbook and it gives a HTML error 400 because of these string declaration.
You can verify here : https://github.com/borgbase/borgbase-api-client/blob/master/borgbase_api_client/mutations.py
REPO_ADD = """
mutation repoAdd(
  $name: String!
  $quota: Int
  $quotaEnabled: Boolean
  $appendOnlyKeys: [String]
  $fullAccessKeys: [String]
  $alertDays: Int
  $region: String!
  $borgVersion: String
  ) {

### CODE REVIEW

**Comment by stroobl** [comment]
I had the same issue and the proposed change in the PR fixed the issue for me. Thanks!

**Comment by adhawkins** [comment]
Apologies for the slow response. Will test here tomorrow and apply this.

Thanks for the interest and taking the time to fix it.

**Comment by adhawkins** [comment]
The changes have failed tests, as the documentation hasn't been updated to reflect the new parameter types.

Can you address this?

**Comment by adhawkins** [comment]
That looks good, test now pass.

Can you merge the two commits into one to keep the commit history a bit cleaner?

**Comment by adhawkins** [comment]
Apologies, I didn't spot that you'd merged those commits. I've now merged this PR to the main branch. Thanks for your contribution.

**Pull request merged**
